name: smp-educontrol-frontend

services:
  smp-educontrol:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smp-educontrol
    ports:
      - "5014:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped