server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Importante para que el routing de Angular funcione correctamente
        try_files $uri $uri/ /index.html;
    }
}